version: '3.8'

services:
  db:
    image: postgres:16
    container_name: test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartclinicdb_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./SmartClinic-Server
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/smartclinicdb_test
      NODE_ENV: test
    depends_on:
      - db
    command: node --experimental-vm-modules node_modules/.bin/jest

volumes:
  postgres_test_data:
