version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartclinicdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
      image: hasanmawasi/smartclinic-backend:${TAG}
      container_name: node-server
      restart: always
      environment:
        DATABASE_URL: postgres://postgres:password@db:5432/smartclinicdb
        NODE_ENV: production
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        JWT_SECRET: ${JWT_SECRET}
      ports: 
        - "5000:5000"
      depends_on:
        - db
      command: sh ./shell.sh
  frontend:
    image: hasanmawasi/smartclinic-frontend:${TAG}
    container_name: frontend
    restart: always
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      -  "80:80"
    depends_on:
      - backend
    
volumes:
  postgres_data: