version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartclinicdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
      build:
        context: ./SmartClinic-Server
        dockerfile: Dockerfile
      container_name: node-server
      restart: always
      environment:
        DATABASE_URL: postgres://postgres:postgres@db:5432/smartclinicdb
        NODE_ENV: production
      ports:
        - "5000:5000"
      depends_on:
        - db
  frontend:
    build:
      context: ./SmartClinic-Web/doctor-app
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      -  "80:80"
    depends_on:
      - backend
    
volumes:
  postgres_data: