name: CICD

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build all services using docker compose
        run: docker compose build

      - name: Push backend image
        run:  docker push hasanmawasi/smartclinic-backend:latest

      - name: Push frontend image
        run: docker push hasanmawasi/smartclinic-frontend:latest
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: SSH into EC2 instance and deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /home/ubuntu/SmartClinic

            # Pull the latest images for backend and frontend
            docker compose pull

            # Stop and remove any old containers
            docker compose down

            # Rebuild the containers (if needed) and start them in detached mode
            docker compose up -d