name: CICD

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build all services using docker compose
        run: docker compose build

      - name: Push backend image
        run:  docker push hasanmawasi/smartclinic-backend:latest

      - name: Push frontend image
        run: docker push hasanmawasi/smartclinic-frontend:latest
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: SSH into EC2 instance and deploy with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      
      - name: Pull backend image from Docker Hub
        run: docker pull hasanmawasi/smartclinic-backend:latest

      - name: Pull frontend image from Docker Hub
        run: docker pull hasanmawasi/smartclinic-frontend:latest

      - name: SSH into EC2 instance and deploy with Docker Compose
        run: |
          ssh -i ${{ secrets.SERVER_SSH_PRIVATE_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd /home/${{ secrets.SERVER_USER }}/SmartClinic
            docker-compose down
            docker-compose up --build -d
          EOF

