name: CICD

on:
  push:
    branches: [stage]  # or main, depending on your workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build all services
        run: docker compose build

      - name: Tag and push backend image
        run: |
          docker tag smartclinic-backend:latest hasanmawasi/smartclinic-backend:latest
          docker push hasanmawasi/smartclinic-backend:latest

      - name: Tag and push frontend image
        run: |
          docker tag smartclinic-frontend:latest hasanmawasi/smartclinic-frontend:latest
          docker push hasanmawasi/smartclinic-frontend:latest

  deploy:
    needs: build
    runs-on: [self-hosted] # Means EC2 is registered as GitHub runner (or can use ssh later)

    steps:
      - name: Pull latest images
        run: |
          docker pull hasanmawasi/smartclinic-backend:latest
          docker pull hasanmawasi/smartclinic-frontend:latest

      - name: Deploy updated services
        run: |
          cd /home/ubuntu/smartclinic-deployment  # wherever you keep docker-compose.yml
          docker-compose down
          docker-compose up -d --remove-orphans
