name: CICD

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build all services using docker compose
        run: docker compose build

      - name: Push backend image
        run:  docker push hasanmawasi/smartclinic-backend:latest

      - name: Push frontend image
        run: docker push hasanmawasi/smartclinic-frontend:latest
  deploy:
    runs-on: [self-hosted]
    needs: build  # This makes sure 'deploy' runs AFTER 'build' finishes
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/SmartClinic
            docker compose pull  # Pull latest images
            docker compose up -d  # Restart containers with new images