name: CICD

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Push backend image
        working-directory: ./SmartClinic-Server 
        run: |
          docker build --no-cache -t hasanmawasi/smartclinic-backend:${{ github.sha }} .
          docker push hasanmawasi/smartclinic-backend:${{ github.sha }}


      - name: Push frontend image
        working-directory: ./SmartClinic-Web/doctor-app 
        run: |
          docker build --no-cache -t hasanmawasi/smartclinic-frontend:${{ github.sha }} .
          docker push hasanmawasi/smartclinic-frontend:${{ github.sha }}
  
  
      
  deploy:
    needs: [build]
    runs-on: [self-hosted , stage]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deep Clean Docker System
        run: |
          docker system prune -a -f --volumes
          docker volume prune -f
          docker image prune -a -f

      - name: Cleanup old containers
        run: |
          docker compose -f docker-compose.prod.yml down || true
          docker system prune -af    

      - name: Pull Latest Images
        run: |
          docker pull hasanmawasi/smartclinic-frontend:${{ github.sha }}
          docker pull hasanmawasi/smartclinic-backend:${{ github.sha }}
      - name: Stop and Remove Old Containers
        run: docker compose -f docker-compose.prod.yml down
      - name: Start Services
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          TAG=${{ github.sha }} docker compose -f docker-compose.prod.yml up -d
      

