name: CICD

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build all services using docker compose
        run: docker compose build

      - name: Push backend image
        run:  docker push hasanmawasi/smartclinic-backend:latest

      - name: Push frontend image
        run: docker push hasanmawasi/smartclinic-frontend:latest
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: SSH into EC2 instance and deploy with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      - name: Pull backend image from Docker Hub
        run: docker pull hasanmawasi/smartclinic-backend:latest

      - name: Pull frontend image from Docker Hub
        run: docker pull hasanmawasi/smartclinic-frontend:latest

      - name: Stop and remove old backend container
        run: docker rm -f node-server || true

      - name: Stop and remove old frontend container
        run: docker rm -f frontend || true

      - name: Run backend container
        run: docker run -d --name node-server -p 5000:5000 hasanmawasi/smartclinic-backend:latest

      - name: Run frontend container
        run: docker run -d --name frontend -p 80:80 hasanmawasi/smartclinic-frontend:latest


